### PR TITLE
added nop object

### PR DESCRIPTION
**Pull request by Graur**
Closes: #7

### CODE REVIEW

**Comment by Graur** [comment]
@yegor256 please, have a look

**Comment by yegor256** [comment]
@Graur please, make it more descriptive

**Comment by Graur** [comment]
@yegor256 Updated. Now it is more descriptive or still not enough?

**Comment by yegor256** [comment]
@Graur I would add a space before `\ff{TRUE}`

**Comment by Graur** [comment]
@yegor256 OMG, thanks! I miss that, my bad

**Comment by Graur** [comment]
@yegor256 Updated. Please, have a look

**Comment by yegor256** [comment]
@Graur also, read about Oxford comma: https://en.wikipedia.org/wiki/Serial_comma

**Comment by Graur** [comment]
@Graur Now I see the ambiguity of my text. Thanks!

**Comment by yegor256** [comment]
@Graur thanks!

**Pull request merged**
