### PR TITLE
Fix chapter 8, Memory

### PR DESCRIPTION
**Pull request by ivan-egorov42**

### CODE REVIEW

**Comment by ivan-egorov42** [comment]
@Graur pls, have a look.

**Comment by Graur** [comment]
@ivan-egorov42 you can link this PR to your issue by mentioning: #16

**Review by Graur — APPROVED** [review]

**Comment by ivan-egorov42** [comment]
@yegor256 please, have a look.

**Comment by yegor256** [comment]
@ivan-egorov42 thanks!

**Pull request merged**
